import "./globals.css";
import { Patrick_Hand } from "next/font/google";
const patrickHand = Patrick_Hand({
	subsets: ["latin"],
	weight: ["400"],
});

export const metadata = {
	title: `Home Epictatus`,
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={patrickHand.className}>{children}</body>
		</html>
	);
}
